apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <NAMESPACE>-deployer
  namespace: <NAMESPACE>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-deployer
subjects:
- kind: ServiceAccount
  name: github
  namespace: default
